# Generated by Django 4.0.6 on 2022-07-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_customuser_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
